CREATE TABLE [dbo].[User]
(
	[UserId]	BIGINT			IDENTITY (1, 1) NOT NULL,
	[UserName]	NVARCHAR(200)	NOT NULL,
	[FullName]	NVARCHAR(200)	NOT NULL,
	CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED ([UserId] ASC)	
)
GO

CREATE UNIQUE INDEX UX_User_UserName ON [dbo].[User](UserName)
GO
